<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZY5AMP7\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZY5AMP7/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZY5AMP7.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZY5AMP7\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerZY5AMP7\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'ZY5AMP7',
    'container.build_id' => '949428d7',
    'container.build_time' => 1655115776,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZY5AMP7');
